version: 2.1
jobs:

orbs:
  cypress: cypress-io/cypress@1
  react: thefrontside/react@0.1.0
  heroku: circleci/heroku@0.0.10
workflows:
  build:
    jobs:
      - cypress/run:
          start: npm start
          wait-on: 'http://localhost:3000'
      - deploy:
          executor: heroku/default
            steps:
              - checkout
              - heroku/install
                - run:
                    command: >
                      echo "The command above installs Heroku, the command below deploys.
                      What you do inbetween is up to you!"
                - heroku/deploy-via-git