jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - cypress/run:
          start: npm start
          wait-on: 'http://localhost:3000'
      - heroku/deploy-via-git
orbs:
  heroku: circleci/heroku@x.y
version: 2.1
workflows:
  heroku_deploy:
    jobs:
      - deploy