jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
orbs:
  heroku: heroku: circleci/heroku@1.2.6
  cypress: cypress-io/cypress@1
version: 2.1
workflows:
  build:
    jobs:
      - cypress/run
  heroku_deploy:
    jobs:
      - deploy