jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git
orbs:
  heroku: circleci/heroku@x.y
version: 2.1
workflows:
  build:
    jobs:
      - cypress/run
  heroku_deploy:
    jobs:
      - deploy